### ISSUE TITLE
Tiling only working in northwest corner?

### ISSUE THREAD

**Issue by franciskafieh** [mcz/openbox#1]
Hey there. Not sure if this project is still active, but for me, setting the tiling argument to any direction makes it go to the northwest automatically.

Here are my binds:
```xml
    <keybind key="W-Left">
      <action name="Tile" direction="s"/>
    </keybind>

    <keybind key="W-Right">
      <action name="Tile" direction="n"/>
    </keybind>

    <keybind key="W-e">
      <action name="Untile"/>
    </keybind>
```

If anyone has got this working, please lmk. thanks so much!

**Comment by mcz** [comment]
Northwest is the default when you don't pick a direction. The correct syntax to do so is:
```xml
<keybind key="W-Left">
  <action name="Tile">
    <direction>"s"</direction>
  </action>
</keybind>
```
This mirrors the syntax of other actions, where arguments are subkeys.

As for whether the project is still active, It is in a state where it does what I want it to do. If my requirements change (and I have the time), activity will pick up. I'd also welcome code from others. One thing to maybe look at is multi-monitor support (something I never did, because it's unnecessary in my setup)

**Comment by franciskafieh** [comment]
Thanks so much! My bad. Love your work :)

EDIT: BTW, should I create a PR to add this to the README? This way nobody else will face the same issue as me of not knowing what to do. Did I miss this info anywhere?
